# Generated by Django 3.2.15 on 2024-07-28 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAvito',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('carburant', models.CharField(blank=True, max_length=50, null=True)),
                ('boite', models.CharField(blank=True, max_length=50, null=True)),
                ('puissance_fiscale', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(max_length=500)),
                ('kilometrage', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre_de_portes', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('autor', models.CharField(default='N/A', max_length=255, null=True)),
                ('etat', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarMoteur',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('carburant', models.CharField(blank=True, max_length=50, null=True)),
                ('boite', models.CharField(blank=True, max_length=50, null=True)),
                ('puissance_fiscale', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(max_length=500)),
                ('kilometrage', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre_de_portes', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('autor', models.CharField(default='N/A', max_length=255, null=True)),
                ('etat', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('carburant_prefere', models.CharField(blank=True, max_length=100, null=True)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('boite_preferee', models.CharField(blank=True, max_length=100, null=True)),
                ('is_user_authenticated', models.CharField(blank=True, max_length=10, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='ConcreteCar',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('carburant', models.CharField(blank=True, max_length=50, null=True)),
                ('boite', models.CharField(blank=True, max_length=50, null=True)),
                ('puissance_fiscale', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(max_length=500)),
                ('kilometrage', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre_de_portes', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('autor', models.CharField(default='N/A', max_length=255, null=True)),
                ('etat', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Concrete Car',
                'verbose_name_plural': 'Concrete Cars',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='admin', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycar.concretecar')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycar.client')),
            ],
            options={
                'verbose_name': 'Client-Car Visite',
                'verbose_name_plural': 'Client-Cars Visites',
                'unique_together': {('client', 'car')},
            },
        ),
        migrations.CreateModel(
            name='Sauvegarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycar.concretecar')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycar.client')),
            ],
            options={
                'verbose_name': 'Client-Car Sauvegarde',
                'verbose_name_plural': 'Client-Cars Sauvegardes',
                'unique_together': {('client', 'car')},
            },
        ),
    ]
