# Generated by Django 3.2.15 on 2024-07-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_user_authenticated',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_activity',
        ),
    ]
