# Generated by Django 3.2.15 on 2024-07-30 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0002_auto_20240728_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sauvegarde',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycar.caravito'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycar.caravito'),
        ),
    ]
